### ISSUE TITLE
Русификация уведомлений

### ISSUE THREAD

**Issue by reserdB** [ITDSystems/alvex-business-calendar#4]
Подскажите пожалуйста, пытаюсь русифицировать уведомления о дедлайне задачи и ее просрочке. Уведомления приходят, но вместо букв иероглифы, хотя уведомления о новой задачи приходят в нормально виде. Пологая что, что то с кодировкой, подскажите куда смотреть

**Comment by aviriel** [comment]
Вероятно, Вы сохранили файлы в кодировке cp1251. Все шаблоны в Alfresco должны быть в utf8. 
Если локализуете файлы properties, а не ftl, то нужно потом еще в ascii все перевести.

**Comment by reserdB** [comment]
проверил кодировку ftl файлов, там она utf8 без BOM, перевел в обычный utf8 в теле письма приходит код файла шаблона письма...
я правильно понимаю, что ftl файлы (где код письма) должны лежать по пути \tomcat\webapps\alfresco\WEB-INF\lib\com.alvexcore.repo.business-calendar-0.3-SNAPSHOT.jar\com\alvexcore\bcal и что править их надо именно там?
И не надо переносить их (как указано в иструкциях некоторых) в Data Dictionary > Email Templates > Workflow Notification?

**Comment by aviriel** [comment]
linked to #2

**Comment by reserdB** [comment]
с этим я разобрался, большое спасибо, дело было действительно в кодировке.
так как ресурсов не много по alfresco и далеко не везде отвечают, задам если можно еще вопрос тут, не совсем по данной теме, просто не знаю куда именно его кинуть
Подскажите пожалуйста, не могу понять почему alfresco сортирует (группирует) документы криво. То есть в примере, создаю документы под названием "1, 2 , 3 и тд до 9" сортирует нормально по возрастанию, но как только добавляю документ под названием 10, он пихает его сразу после "1" , то есть получается 1, 10, 2, 3 и тд. так происходит при любой группировке....по имени, названию и тд Подскажите пожалуйста, куда смотреть и где исправить это

**Comment by avasyukov** [comment]
В сортировке сравнение строк посимвольно. Добивайте спереди нулями, будет корректно - "000", "001", ...., "009", "010", ... .
